FROM docker.elastic.co/logstash/logstash-oss:8.11.2

RUN rm -rf /usr/share/logstash/pipeline

COPY logstash/pipeline/production.conf /usr/share/logstash/pipeline/production.conf

ENV PIPELINE_WORKERS=1

EXPOSE 3001