FROM amazoncorretto:17

ENV PATH /opt/kafka/bin:$PATH
ENV KAFKA_DIR "/opt/kafka"

ARG KAFKA_VERSION="2.13-3.6.1"

RUN wget https://dlcdn.apache.org/kafka/3.6.1/kafka_${KAFKA_VERSION}}.tgz -P /opt

RUN ln -s /opt/kafka_${KAFKA_VERSION} ${KAFKA_DIR} 

ADD kafka-manager.sh ${KAFKA_DIR}/bin/kafka-manager

ADD conf/kraft/* ${KAFKA_DIR}/config/kraft/

ENV KAFKA_ACTION=create-topic
ENV KAFKA_TOPIC=prices
ENV KAFKA_SERVER=kafka-server:9092

ENTRYPOINT [ "kafka-manager" ]